# Nombre de la aplicación Spring Boot
spring.application.name=app-movil-g1-parcial

# Puerto en el que se ejecutará el servidor
server.port=9000

# URL de conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/movil_pacial_c2
# Usuario para la conexión a la base de datos
spring.datasource.username=root
# Contraseña para la conexión a la base de datos
spring.datasource.password=abcd1234
# Clase del driver JDBC para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de Hibernate para la creación y eliminación de tablas en la base de datos
spring.jpa.hibernate.ddl-auto=create-drop